name: Deploy Frontend

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: codespace-editor-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .env.production from GitHub Secret
      run: |
        echo "${{ secrets.REACT_ENV_PRODUCTION }}" > .env.production

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }} .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}

    - name: Prepare SSH Bastion tunnel
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.BASTION_PRIVATE_KEY }}" > ~/.ssh/bastion.pem
        chmod 600 ~/.ssh/bastion.pem
        
        # Create SSH config file
        cat > ~/.ssh/config << 'EOF'
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null

        Host bastion
          HostName ${{ secrets.BASTION_HOST }}
          User ${{ secrets.BASTION_USER }}
          IdentityFile ~/.ssh/bastion.pem
          Port 22

        Host ec2
          HostName ${{ secrets.EC2_PRIVATE_IP }}
          User ${{ secrets.EC2_USER }}
          IdentityFile ~/.ssh/bastion.pem
          ProxyCommand ssh -W %h:%p bastion
          Port 22
        EOF

        # Debug: Show the SSH config file contents
        echo "SSH Config file contents:"
        cat ~/.ssh/config

    - name: Test Bastion Connection
      run: |
        ssh -v bastion 'echo "Bastion connection successful"'

    - name: Deploy to EC2 via Bastion
      run: |
        ssh -v ec2 -T << 'EOSSH'
          set -e
          
          # Pull and run the Docker container
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          docker stop frontend || true && docker rm frontend || true
          docker run -d --name frontend -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
        EOSSH
